//zboxscript/lazypoints/include.zs

#include "zboxscript/lazypoints/zc_Dispatcher.zs"
#include "zboxscript/lazypoints/zc_PlayerScore.zs"
#include "zboxscript/lazypoints/zc_Timer.zs"
#include "zboxscript/lazypoints/zc_TimerBonus.zs"
#include "zboxscript/lazypoints/zc_HealthBonus.zs"
#include "zboxscript/lazypoints/zc_Counter.zs"
#include "zboxscript/lazypoints/zc_MapScore.zs"
#include "zboxscript/lazypoints/zc_ScoreStorage.zs"
#include "zboxscript/lazypoints/zc_Spawner.zs"
#include "zboxscript/lazypoints/zc_MapScoreItem.zs"
#include "zboxscript/lazypoints/zc_View.zs"
#include "zboxscript/lazypoints/zc_TimerView.zs"
#include "zboxscript/lazypoints/zc_BonusView.zs"
#include "zboxscript/lazypoints/zc_TallyView.zs"
#include "zboxscript/lazypoints/zc_StaticView.zs"
#include "zboxscript/lazypoints/zc_TopHintView.zs"
#include "zboxscript/lazypoints/zc_Top.zs"
#include "zboxscript/lazypoints/zc_OptionMenuScoreItem.zs"
#include "zboxscript/lazypoints/zc_FontUser.zs"
#include "zboxscript/lazypoints/zc_Parameters.zs"