//zboxscript/quest/trashcan.zsc

//not to be confused with "trash".
//this item should be deposited into "Trash Can".

CLASS TrashBag : Inventory
{
	Default
	{
		Height 32;
		Radius 16;
		Inventory.PickupMessage "$YOUGOTTRASH";
		Inventory.InterHubAmount 0; //you can no longer carry trash with you across levels. im sorry.
		+INVENTORY.ALWAYSPICKUP;
		//$Category "Box Party/Quest/"
	}
	
	States
	{
		Spawn:
			TRCN A 1;
			TRCN A -1;
			Stop;
	}
}