//zboxscript/achievements/scriptedevents.zsc

class box_scriptedevent : box_Achievement
{
	Default
	{
		box_Achievement.title "";
		box_Achievement.name "";
		box_Achievement.borderColor 0x000000;
		box_Achievement.boxColor    0x808080;
	}
}

class youarebeingwatched : box_scriptedevent
{
	Default
	{
		box_Achievement.title "$YOUFEELLIKEYOU";
		box_Achievement.name "$AREBEINGWATCHED";
		box_Achievement.boxColor    0x400000;
	}
}